### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by VoidWhisperer** [staab/git-chat#2]
What exactly is stopping someone from logging into the github account that you have exposed in the code and just deleting the repository?

**Comment by TimWolla** [comment]
see also: https://news.ycombinator.com/item?id=12764059

Basically: Nothing but your moral.

**Comment by VoidWhisperer** [comment]
@TimWolla I commented on your pull request with a possible way to get around github deleting the oauth token

**Comment by staab** [comment]
Yep, you can use this with a private git repository and collaborators and such by forking the project, which would allow security, but the way it's set up here it's completely insecure. Incidentally, over the weekend someone did in fact delete the chat messages repository.
